# gpu
vo=gpu-next
gpu-api=vulkan
hwdec=auto-safe

# sub
sub-auto=fuzzy # 启用模糊搜索

# high-quality
profile=high-quality # 高品质

# ui
osc=no
osd-bar=no
border=no

# quit
save-position-on-quit=yes
keep-open=yes

# volume
volume=100
volume-max=200
watch-later-options-remove=volume
