[mgr]
show_hidden = true
linemode = "size"

[opener]
# edit = [{ run = "nvim %s", block = true, for = "unix" }]

onlyoffice = [
  { run = "GTK_IM_MODULE=fcitx onlyoffice-desktopeditors %s", orphan = true },
]


[open]
prepend_rules = [
  { url = "*.{ppt,docx,xlsx,pptx,odt,ods,odp,doc}", use = [
    "onlyoffice",
  ] },
]
